version: "3.8"

services:
    postgres:
        image: postgres
        container_name: workopia_postgres_container
        restart: always
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=mustafa
            - POSTGRES_DB=workopia
        ports:
            - "5432:5432"
        volumes:
            - postgres:/var/lib/postgresql/data

    pgadmin:
        image: dpage/pgadmin4
        restart: always
        container_name: workopia_pgadmin_container
        environment:
            - PGADMIN_DEFAULT_EMAIL=admin@admin.com
            - PGADMIN_DEFAULT_PASSWORD=admin
        depends_on:
            - postgres
        ports:
            - "5050:80"
        volumes:
            - pgadmin:/var/lib/pgadmin

volumes:
    postgres:
    pgadmin:
